return {
  pde = {
    ai = true,
    angular = false,
    cpp = true,
    csharp = false,
    docker = true,
    elixir = false,
    flutter = false,
    go = true,
    html = true,
    java = false,
    json = true,
    julia = false,
    jupyter = true,
    lua = true,
    nix = true,
    python = true,
    r = false,
    react = true,
    ruby = false,
    rust = true,
    solidity = false,
    svelte = false,
    tailwind = true,
    terraform = false,
    typescript = true,
    vuejs = false,
  },
}
